server:
  port: 12001

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: circle0124
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.xml
